<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AMT.Domain\AMT.Domain.csproj" />
    <ProjectReference Include="..\AMT.Infrastructure\AMT.Infrastructure.csproj" />
  </ItemGroup>

</Project>
