<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AMT.Domain\AMT.Domain.csproj" />
    <ProjectReference Include="..\AMT.Infrastructure\AMT.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\Extentions\" />
    <Folder Include="Services\" />
    <Folder Include="Services\Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
  </ItemGroup>

</Project>
